<?php

/**
 * @author Kashyap Team
 * @copyright Copyright (c) 2018 Kashyap (http://kashyapsoftware.com/)
 * @package Kashyap_GoogleAnalytics
*/

?>
<!-- Ks Google Code for eCommerce  -->
<script>
    /* <![CDATA[ */

	ga('ecommerce:addTransaction', {
		'id': '<?= $block->getOrderId();?>',                     // Transaction ID. Required.
		'affiliation': '<?= $block->getOrderStoreName(); ?>',   // Affiliation or store name.
		'revenue': '<?= $block->getGrandTotal();?>',               // Grand Total.
		'shipping': '<?= $block->getShippingAmount();?>',                  // Shipping.
		'tax': '<?= $block->getTaxAmount();?>'                     // Tax.
	});

	<?php foreach($block->getOrderItems() as $orderItem):?>
	ga('ecommerce:addItem', {
		'id': '<?= $block->getOrderId();?>',                     // Transaction ID. Required.
		'name': '<?= $block->cleanUpValue($orderItem->getName());?>',    // Product name. Required.
		'sku': '<?= $orderItem->getSku();?>',                 // SKU/code.
		'price': '<?= $orderItem->getPrice();?>',                 // Unit price.
		'quantity': '<?= $orderItem->getQtyOrdered();?>'                   // Quantity.
	});
	<?php endforeach; ?>

	ga('ecommerce:send');
	ga('second.ecommerce:send');


	/* ]]> */
</script>
<!-- END Google Code for eCommerce  -->
