<?php

/**
 * @author Kashyap Team
 * @copyright Copyright (c) 2018 Kashyap (http://kashyapsoftware.com/)
 * @package Kashyap_GoogleAnalytics
*/

    $helperObj = $block->getHelperObject();
    if($helperObj->isEnabled()) :
?>
    <!-- Ks Google Analytics-->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','<?php echo !$this->getDebug() ? '//www.google-analytics.com/analytics.js' : 'https://www.google-analytics.com/analytics_debug.js';?>','ga');

        <?php if($helperObj->getDebug()): ?>
            window.ga_debug = {trace: true};
        <?php endif;?>

        ga('create', '<?= $helperObj->getMainTracking()?>', 'auto');

        <?php if($helperObj->getLinkAttribution()):?>
            ga('require', 'linkid');
        <?php endif;?>

        ga('require', 'ec');

        <?php if($helperObj->getIpAnonymization()):?>
            ga('set', 'anonymizeIp', true);
        <?php endif;?>

        ga('send', 'pageview');

        <?php if($helperObj->getSecondTracking()){ ?>
            ga('create', '<?= $helperObj->getSecondTracking();?>', 'auto', {'name': 'second'});
            ga('second.send', 'pageview');
        <?php } ?>
    </script>

<?php endif; ?>